version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq-gs'
    ports:
      - "5672:5672"  # Porta da aplicação
      - "15672:15672" # Porta da interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest